# Dependencies
markdown:         
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Projects
tagline:          'Ali Haider'
description:      'Forked: <a href="https://github.com/poole/hyde" target="_blank">hyde</a>.'
url:              https://alihaider1264.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alihaider1264/alihaider1264.github.io
